[package]
name = "telegram_typing_bot"
version = "0.1.0"
authors = ["Kilerd <blove694@gmail.com>"]
edition = "2018"
description = "yet another async telegram bot framework"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
